# model
model_name_or_path: /root/autodl-tmp/hug/models--Qwen--Qwen1.5-0.5B/snapshots/8f445e3628f3500ee69f24e1303c9f10f5342a39
#model_name_or_path: /media/xk/D6B8A862B8A8433B/data/qwen2_05b
# method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

# dataset
dataset: alpaca_gpt4_data_zh_modified_del
dataset_dir: /root/autodl-tmp/LLaMA-Factory/data
template: default
cutoff_len: 1024
#max_samples: 1000
# temperature: 0.1
do_sample: false
overwrite_cache: true
preprocessing_num_workers: 2

# output
output_dir: /root/autodl-tmp/LLaMA-Factory/output/Yi-6B-chat/sft
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.01
fp16: true
max_steps: 500
save_total_limit: 1

# eval
val_size: 0.1
per_device_eval_batch_size: 4
evaluation_strategy: steps
eval_steps: 100

