# 训练奖励模型
### model
# model_name_or_path: /root/autodl-tmp/hug/models--Qwen--Qwen2-7B-Instruct/snapshots/f2826a00ceef68f0f2b946d945ecc0477ce4450c
model_name_or_path: /root/autodl-tmp/hug/models--Qwen--Qwen-7B-chat/snapshots/93a65d34827a3cc269b727e67004743b723e2f83

### method
stage: rm
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: mingzhu_DPO
dataset_dir: /root/autodl-tmp/LLaMA-Factory/data
template: default
cutoff_len: 1024
# max_samples: 3000
overwrite_cache: true
preprocessing_num_workers: 1
# temperature: 0.1
do_sample: false

### output
output_dir: /root/autodl-tmp/LLaMA-Factory/output/rm
logging_steps: 1
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 8.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.01
fp16: true
max_steps: 1000
ddp_timeout: 180000000
save_total_limit: 3

### eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 100

