# model
reward_model: /root/autodl-tmp/LLaMA-Factory/output/rm
# checkpoint_dir: /root/autodl-tmp/LLaMA-Factory/output/merge
model_name_or_path: /root/.cache/temp

# method
stage: ppo
do_train: true
finetuning_type: lora
lora_target: all

# dataset
dataset: SanGuoYanyi_Parallel
dataset_dir: /root/autodl-tmp/LLaMA-Factory/data
template: default
cutoff_len: 1024
max_samples: 2000
overwrite_cache: true
preprocessing_num_workers: 1
# temperature: 0.1
do_sample: false
overwrite_cache: true

# output
output_dir: /root/autodl-tmp/LLaMA-Factory/output/ppo
logging_steps: 1
save_steps: 25
plot_loss: true
overwrite_output_dir: true

# train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 2
bf16: true
# load_8bit: true
max_steps: 100
save_total_limit: 3
ddp_timeout: 180000000




### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9